baseurl = "https://derekcochran.dev/"
title = "Derek Cochran"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Derek Cochran"
  info = "Software Engineer"
  description = "Derek Cochran's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.webp"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2022

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Skylark95/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/Skylark95/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/Skylark95/"
[[params.social]]
  name = "Facebook"
  icon = "fa fa-facebook fa-2x"
  weight = 3
  url = "https://facebook.com/derek.cochran/"

[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
# [[menu.main]]
#   name = "Categories"
#   weight = 2
#   url  = "categories/"
# [[menu.main]]
#   name = "Tags"
#   weight = 2
#   url  = "tags/"